#pragma once
// DeltaProfileHourlyParams.h -- the tunable numbers of lsDeltaProfileHourly (DLT-H).
// SHIPPED DEFAULTS (1.0.0): the intraday Delta Profile 2.5.4 rules, scaled from its 90-minute window on 3-minute bars to a
// 24-trading-hour window on the hourly chart (zones: the newest 2/3 of the window, as 60 of 90 minutes in 2.5.4).
// From the first adopted refit on, this file is REGENERATED by the LRA nightly (analytics/lra/dph_nightly.py): written into
// the plugin folder only when the judge accepted a variant on sessions that did not pick it. The build job rebuilds on change.
namespace dphp {
static const char* const PARAMS_ID = "default-1.0.0";
static const int WINDOW_HOURS = 24;          // the profile: the host bars that make up the last 24 trading hours
static const int ZONE_HOURS = 16;            // zones: the newest 16 of those hours
static const double NODE_MIN_RATIO = 2.0;    // a node: |row delta| >= 2.0 x the average |row delta|
static const double FORM_SHARE = 0.10;       // a bar takes part in a node when its delta there is >= 10% of the node's net
static const double ZONE_HEAVY = 0.25;       // zone rows: |delta| >= 25% of the largest row
static const double ZONE_SHARE = 0.40;       // a zone holds >= 40% of all selling (or buying) in the zone window
static const double ZONE_EDGE = 0.25;        // ... and sits in the top (selling) / bottom (buying) 25% of the range
static const int ZONE_GAP_TICKS = 2;         // zone rows may skip one missing tick
// Markets whose hourly A passed the all-market study (checklist #21). Every other market shows TESTING in the header.
static const char* const PROVEN_MARKETS = "";
}  // namespace dphp
