// generated by on_vwap_study 1.1.0 (2026-10-09) on 2026-10-09 07:50 from data/session/on_touch - do not edit
#pragma once
struct OTParams { const char* m; int win; double nu, k; int ready; };
static const OTParams OT_PARAMS[] = {
  { "ES", 20, 0.3500, 1.0000, 0 },
  { "NQ", 40, 0.2000, 1.0000, 0 },
  { "CL", 20, 0.3500, 1.0000, 0 },
  { "NG", 20, 0.3500, 1.0000, 0 },
  { "GC", 20, 0.3500, 1.0000, 0 },
  { "HG", 20, 0.3500, 1.0000, 0 },
  { "EU", 20, 0.3500, 1.0000, 0 },
};
static const int OT_N = 7;
