#!/usr/bin/env python3
"""gen_hodlod_events.py - bake the economic-calendar days (events_2025_2026.csv) into HodLodEvents.h for lsHodLod.

Run nightly (after the events file is refreshed):  python gen_hodlod_events.py <events.csv> <out HodLodEvents.h>

One row per (date, event).  Bits: CPI, NFP, FOMC, ISM_MFG (every market) + EIA_CRUDE (CL) / EIA_GAS (NG) - the same sets as
hodlod_read.py / studies.py (NEWS_ALL, NEWS_EXTRA).  Rows with any `status` are used (the read model and the studies use all).
The header records the last date the file covers: a later session is "calendar unknown" (news 0, flagged in the status file),
never guessed.
"""
import csv
import hashlib
import sys

BITS = {"CPI": 1, "NFP": 2, "FOMC": 4, "ISM_MFG": 8, "EIA_CRUDE": 16, "EIA_GAS": 32}


def main(src: str, out: str) -> None:
    raw = open(src, "rb").read()
    days: dict = {}
    skipped = 0
    with open(src, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            d, e = (r.get("date") or "").strip()[:10], (r.get("event") or "").strip()
            if len(d) != 10 or e not in BITS:
                skipped += 1
                continue
            k = int(d.replace("-", ""))
            days[k] = days.get(k, 0) | BITS[e]
    if not days:
        raise SystemExit("no events read from " + src)
    keys = sorted(days)
    L = []
    A = L.append
    A("// HodLodEvents.h - GENERATED by gen_hodlod_events.py - do not edit by hand. Regenerated nightly from")
    A("// events_2025_2026.csv (sha256 %s, %d days, %d rows skipped)." % (hashlib.sha256(raw).hexdigest()[:16], len(keys), skipped))
    A("// The economic calendar of the HOD / LOD models: hle news = CPI / NFP / FOMC / ISM-mfg (+ EIA crude for CL, EIA gas for NG);")
    A("// hlr timing fomc = FOMC, amnews = CPI or NFP; hlr::fomcPause on FOMC days.  Pure C++14 / ASCII.")
    A("#pragma once")
    A("namespace hlev {")
    A("enum { CPI = 1, NFP = 2, FOMC = 4, ISM_MFG = 8, EIA_CRUDE = 16, EIA_GAS = 32 };")
    A("static const int kFirstDay = %d, kLastDay = %d;   // yyyymmdd covered by the file; outside = unknown" % (keys[0], keys[-1]))
    A("static const int kN = %d;" % len(keys))
    A("static const int kDay[kN] = {")
    for i in range(0, len(keys), 10):
        A("  " + ", ".join(str(k) for k in keys[i:i + 10]) + ",")
    A("};")
    A("static const unsigned char kBits[kN] = {")
    for i in range(0, len(keys), 20):
        A("  " + ", ".join(str(days[k]) for k in keys[i:i + 20]) + ",")
    A("};")
    A("// the bits on yyyymmdd; known = false when the date is outside the file (then bits = 0 and the caller flags it)")
    A("inline unsigned bitsOn(int ymd, bool& known) {")
    A("  known = ymd >= kFirstDay && ymd <= kLastDay;")
    A("  int lo = 0, hi = kN - 1;")
    A("  while (lo <= hi) { int m = (lo + hi) / 2; if (kDay[m] == ymd) return kBits[m]; if (kDay[m] < ymd) lo = m + 1; else hi = m - 1; }")
    A("  return 0;")
    A("}")
    A("// the market's news set (hle State.news): market index 0 ES 1 NQ 2 CL 3 GC 4 HG 5 NG 6 EU (hl::MKTS / hlr::Market)")
    A("inline bool newsDay(int market, unsigned bits) {")
    A("  unsigned m = CPI | NFP | FOMC | ISM_MFG;")
    A("  if (market == 2) m |= EIA_CRUDE;")
    A("  if (market == 5) m |= EIA_GAS;")
    A("  return (bits & m) != 0;")
    A("}")
    A("inline bool fomcDay(unsigned bits) { return (bits & FOMC) != 0; }")
    A("inline bool amNews(unsigned bits) { return (bits & (CPI | NFP)) != 0; }")
    A("}  // namespace hlev")
    open(out, "w", newline="\n").write("\n".join(L) + "\n")
    print("wrote %s: %d days %d..%d" % (out, len(keys), keys[0], keys[-1]))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2])
