#!/usr/bin/env python3
"""gen_hodlod_medians.py - bake the TYPICAL (median) first-extreme timing per market into plugin/HodLodMedians.h (v12 E row).

Source: the studies agent's per-session tables, hodlod_studies/out/studies/sessions_<MKT>.csv (studies.py session_table: complete
RTH sessions, each market's own open, bar END stamps, minutes since the nominal open):
    y_t1   minutes since open of the first final extreme      y_t_rec  minutes since open of the opening reclaim (-1 = none)
    y_wick |open - first extreme| (price)                     y_hod_first  1 = the HOD printed first
Medians, never means (ES: took mean 45m vs median 21m; rec. took mean 28m vs median 9m), for all sessions and by first side.
Rec. Took = y_t_rec - y_t1 over the sessions that reclaimed.

    python gen_hodlod_medians.py <studies/out/studies dir> <out HodLodMedians.h>
Deterministic; exits 1 without writing when a market file or column is missing.
"""
import csv, hashlib, math, os, statistics, sys

MARKETS = ("ES", "NQ", "CL", "GC", "HG", "NG", "EU")
NB, MIN_N = 12, 20


def med(v):
    v = [x for x in v if math.isfinite(x)]
    return statistics.median(v) if v else float("nan")


def main(argv):
    if len(argv) != 3:
        print(__doc__); return 2
    src, out = argv[1], argv[2]
    rows, shas, gapsOut, recW = {}, [], {}, {}
    for m in MARKETS:
        p = os.path.join(src, "sessions_%s.csv" % m)
        raw = open(p, "rb").read(); shas.append(hashlib.sha256(raw).hexdigest()[:8])
        R = list(csv.DictReader(raw.decode("utf-8").splitlines()))
        for c in ("y_t1", "y_t2", "y_t_rec", "y_wick", "y_hod_first"):
            if not R or c not in R[0]:
                print("missing column %s in %s" % (c, p)); return 1
        def grp(sel):
            S = [r for r in R if sel(r)]
            t1 = [float(r["y_t1"]) for r in S]
            rt = [float(r["y_t_rec"]) - float(r["y_t1"]) for r in S if float(r["y_t_rec"]) >= 0]
            wk = [float(r["y_wick"]) for r in S]
            return (len(S), med(t1), med(rt), med(wk))
        rows[m] = (grp(lambda r: True), grp(lambda r: r["y_hod_first"] == "0"), grp(lambda r: r["y_hod_first"] == "1"))
        # (v13) Gap = 2nd - 1st extreme (y_t2 - y_t1): all sessions and by the 1st extreme's 30-min bucket, bucket k = t1 in
        # (15 + 30(k-1), 15 + 30k] (k = 0: t1 <= 15); a bucket with fewer than MIN_N sessions falls back to all (-1 here)
        def q(v, p):
            v = sorted(v); return statistics.quantiles(v, n=4)[0 if p == 25 else 2] if len(v) >= 4 else float("nan")
        gaps = [(float(r["y_t1"]), float(r["y_t2"]) - float(r["y_t1"])) for r in R]
        allg = [g for _, g in gaps]
        bk = []
        for k in range(NB):
            lo, hi = (-1e9, 15.0) if k == 0 else (15.0 + 30 * (k - 1), 15.0 + 30 * k)
            v = [g for t, g in gaps if lo < t <= hi]
            bk.append((len(v), med(v), q(v, 25), q(v, 75)) if len(v) >= MIN_N else (len(v), -1.0, -1.0, -1.0))
        gapsOut[m] = ((len(allg), med(allg), q(allg, 25), q(allg, 75)), bk)
        # (v15) the reclaim window: W = the 75th percentile of (reclaim - 1st extreme) over ALL sessions (no reclaim = never),
        # rounded up to the 3-min grid; P = the share of sessions reclaiming within W (all / the later half by date)
        R2 = sorted(R, key=lambda r: r["date"])
        rt = [(float(r["y_t_rec"]) - float(r["y_t1"])) if float(r["y_t_rec"]) >= 0 else math.inf for r in R2]
        srt = sorted(rt); n = len(srt)
        def pct(p):   # numpy 'linear' percentile, inf-aware
            x = (n - 1) * p / 100.0; lo = int(math.floor(x)); hi = min(lo + 1, n - 1); f = x - lo
            a, b = srt[lo], srt[hi]
            return a if f == 0 or a == b else (math.inf if math.isinf(b) else a + (b - a) * f)
        W = int(math.ceil(pct(75) / 3.0) * 3)
        late = rt[n // 2:]
        recW[m] = (W, sum(1 for x in rt if x <= W) / n, sum(1 for x in late if x <= W) / len(late), pct(25), pct(50), pct(75), pct(90))
    L = ["// HodLodMedians.h - GENERATED by tools/gen_hodlod_medians.py - do not edit by hand (the nightly job can regenerate it).",
         "// Source: the studies' per-session tables sessions_<MKT>.csv (sha256/8 %s), each market's own RTH open." % " ".join(shas),
         "// Typical (median) values for the v12 E row: t1 = minutes from the open to the first final extreme, recTook = minutes from the",
         "// first extreme to the opening reclaim (reclaiming sessions only), size = |first extreme - open| in price. [0] all sessions,",
         "// [1] LOD printed first, [2] HOD printed first.",
         "#ifndef HODLOD_MEDIANS_H", "#define HODLOD_MEDIANS_H", "namespace hlm {",
         "struct Med { int n; double t1, recTook, size; };",
         "struct Gap { int n; double med, p25, p75; };   // minutes; med -1 = too few sessions (use all)",
         "struct RecWin { int w; double p, pLate, q25, q50, q75, q90; };   // (v15) reclaim within w min of the 1st extreme on p of sessions",
         "struct MarketMed { const char* m; Med g[3]; Gap gapAll; Gap gapBucket[%d]; RecWin rec; };   // bucket k: t1 in (15+30(k-1), 15+30k]" % NB,
         "static const MarketMed HLM[7] = {"]
    for m in MARKETS:
        g = rows[m]
        ga, gb = gapsOut[m]
        L.append("    { \"%s\", { %s },\n      { %d, %.1f, %.2f, %.2f }, { %s },\n      { %d, %.4f, %.4f, %.1f, %.1f, %.1f, %.1f } }," % (m, ", ".join("{ %d, %.1f, %.1f, %.10g }" % x for x in g), ga[0], ga[1], ga[2], ga[3],
                 ", ".join("{ %d, %.1f, %.2f, %.2f }" % x for x in gb), *recW[m]))
    L += ["};",
          "static const int HLM_NB = %d;" % NB,
          "inline int gapBucketOf(double t1) { if (t1 <= 15) return 0; int k = (int)((t1 - 15 + 29.999999) / 30); return k < HLM_NB ? k : -1; }",
          "inline const MarketMed* medFor(const char* m) { for (int i = 0; i < 7; i++) { const char* a = HLM[i].m; const char* b = m; while (*a && *a == *b) { a++; b++; } if (!*a && !*b) return &HLM[i]; } return 0; }",
          "}  // namespace hlm", "#endif"]
    tmp = out + ".tmp"
    with open(tmp, "w", newline="\n") as f:
        f.write("\n".join(L) + "\n")
    os.replace(tmp, out)
    print("wrote", out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
